#
# Install bash completion for Bazel
#
FROM debian:bullseye-slim AS bazel_builder

ENV BAZEL_VERSION={{bazel_version}}

USER root

RUN apt update \
    && apt install -y curl

#   Add a bazel repository to install bazel and install bazel
RUN install -m 0755 -d /usr/local/share/keyrings \
    && curl -fsSL https://bazel.build/bazel-release.pub.gpg -o /usr/local/share/keyrings/bazel-release.pub.asc \
    && chmod a+r /usr/local/share/keyrings/bazel-release.pub.asc \
    && echo "deb [arch=amd64 signed-by=/usr/local/share/keyrings/bazel-release.pub.asc] https://storage.googleapis.com/bazel-apt stable jdk1.8" > /etc/apt/sources.list.d/bazel-release.list \
    && apt update \
    && apt-get install -y bazel=${BAZEL_VERSION}
#   Copy the bash completion file under /opt/bazel/bash_completion.d
RUN mkdir -p /opt/bazel/bash_completion.d \
    && chmod 0755 /opt/bazel/bash_completion.d \
    && cp /etc/bash_completion.d/bazel /opt/bazel/bash_completion.d/bazel.${BAZEL_VERSION}
